version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
      - redis
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    working_dir: /application
    volumes:
      - .:/application
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: budget_my_funds
      MYSQL_USER: budgetmyfunds
      MYSQL_PASSWORD: budgetmyfunds
      MYSQL_ROOT_PASSWORD: budgetmyfunds
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    env_file:
      - ./.env
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: ./phpdocker/php/Dockerfile
    container_name: php
    working_dir: /application
    volumes:
      - .:/application
      - ./phpdocker/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    ports:
      - "9000:9000"
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    ports:
        - 6379:6379
