# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
defaults: &defaults
  working_directory: ~/laravel
  docker:
    - image: circleci/php:7.1-apache-node-browsers-legacy

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential curl
            curl -sS https://getcomposer.org/installer -o composer-setup.php
            sudo php composer-setup.php --install-dir=/usr/local/bin/ --filename=composer
            sudo pip install awsebcli --upgrade
            sudo /usr/local/bin/composer install -n --prefer-dist
            sudo wget https://phar.phpunit.de/phpunit-7.phar
            sudo chmod +x phpunit-7.phar
            sudo mv phpunit-7.phar /usr/local/bin/phpunit

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      # # run tests!
      # - run:
      #     name: Run available tests
      #     command: phpunit
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: circleci-IAM-keys
          filters:
            branches:
              only:
                - staging
                - master
